import { Geist, Geist_Mono } from "next/font/google";
import Image from 'next/image'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Image className="backgroundImage" src='backgroundmtholly.svg' alt="Background image of Mount Holly" width="2000" height="2000" /> */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          backgroundImage: `url(backgroundmtholly.svg)`,
          backgroundPosition: "center",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          width: "100vw",
          width: "100vh",
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}>
        {children}
      </body>
    </html>
  );
}
